language: c

os:
    - linux
    - osx

cache:
    directories:
        - "$HOME/.nimble"
        - "$HOME/.choosenim"

install:
    - export CHOOSENIM_NO_ANALYTICS=1
    - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
    - sh init.sh -y
    - export PATH=~/.nimble/bin:$PATH
    - choosenim stable

script:
    - nimble test -y

notifications:
    email: false
